apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "pvc-autoresizer.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pvc-autoresizer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pvc-autoresizer
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pvc-autoresizer
    spec:
      serviceAccountName: {{ template "pvc-autoresizer.fullname" . }}-controller
      containers:
        - name: pvc-autoresizer
          command:
            - /pvc-autoresizer
          args:
            - --prometheus-url=http://prometheus-prometheus-oper-prometheus.prometheus.svc:9090
            - --interval=10s
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          {{- with .Values.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          resources:
            requests:
              cpu: 100m
              memory: 20Mi
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
      terminationGracePeriodSeconds: 10
