image:
  # image.repository -- pvc-autoresizer image repository to use.
  repository: quay.io/topolvm/pvc-autoresizer

  # image.tag -- pvc-autoresizer image tag to use.
  # @default -- `{{ .Chart.AppVersion }}`
  tag:  # 0.1.5

  # image.pullPolicy -- TopoLVM image pullPolicy.
  pullPolicy:  # Always

controller:
  replicas: 1
  args:
    - --prometheus-url=http://prometheus-prometheus-oper-prometheus.prometheus.svc:9090
    - --interval=10s
  resources:
    requests:
      cpu: 100m
      memory: 20Mi
  terminationGracePeriodSeconds: 10
