name: "e2e"
on:
  pull_request:
    paths-ignore:
        - "**/*.md"
        - "CODEOWNERS"
  push:
    paths-ignore:
        - "**/*.md"
        - "CODEOWNERS"
    branches:
      - "main"
jobs:
  e2e-k8s:
    name: "e2e-k8s"
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        test_kubernetes_target: ["current", "prev", "prev2"]
    env:
      TEST_KUBERNETES_TARGET: "${{ matrix.test_kubernetes_target }}"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - run: make -C e2e setup
      - run: make -C e2e init-cluster
      - run: make -C e2e test
